### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletouse
name: GetQubitsAvailableToUse
type: operation
namespace: microsoft.quantum.environment
summary: Devolve o número de qubits atualmente disponíveis para utilização.
syntax: 'operation GetQubitsAvailableToUse () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      O número de qubits que poderiam ser atribuídos em `using` comunicado.

      Se a máquina-alvo utilizada não fornecer estas informações, `-1` então é devolvida.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletoborrow
metadata:
  ms.openlocfilehash: 0a6add52244bc38c3e74e5280c3ef007a22c94c7
  ms.sourcegitcommit: d6ac6f4345be0dd68f1bcd944f44b08e7a3cf346
  ms.translationtype: MT
  ms.contentlocale: pt-PT
  ms.lasthandoff: 09/02/2020
  ms.locfileid: "89336809"
