### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletoborrow
name: GetQubitsAvailableToBorrow
type: operation
namespace: Microsoft.Quantum.Environment
summary: >-
  Devolve o número de qubits atualmente disponíveis para pedir emprestado.

  Isto inclui qubits não utilizados; isto é, isto inclui os `GetQubitsAvailableToUse`qubits devolvidos por .
syntax: 'operation GetQubitsAvailableToBorrow () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      O número de qubits que poderiam ser atribuídos em comunicado. `borrowing`

      Se a máquina-alvo que está a `-1` ser utilizada não fornecer estas informações, então é devolvida.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletouse
metadata:
  ms.openlocfilehash: 99dd2afb66c334b112a2ee511b0437281da6b888
  ms.sourcegitcommit: db23885adb7ff76cbf8bd1160d401a4f0471e549
  ms.translationtype: MT
  ms.contentlocale: pt-PT
  ms.lasthandoff: 05/01/2020
  ms.locfileid: "82682417"
