### YamlMime:QSharpNamespace
functions: []
name: Microsoft.Quantum.Environment
newtypes: []
operations:
- summary: Devolve o número de qubits atualmente disponíveis para empréstimo.
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToBorrow
- summary: Devolve o número de qubits atualmente disponíveis para utilização.
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToUse
summary: Estas funções fornecem informações sobre o ambiente em que ocorra a computação quântica.
uid: Microsoft.Quantum.Environment
metadata:
  ms.openlocfilehash: 87e1659f8ecdd6df99271f7552f683ffed85b151
  ms.sourcegitcommit: a87c1aa8e7453360025e47ba614f25b02ea84ec3
  ms.translationtype: MT
  ms.contentlocale: pt-PT
  ms.lasthandoff: 11/26/2020
  ms.locfileid: "96201449"
