### YamlMime:QSharpNamespace
uid: microsoft.quantum.environment
name: Microsoft.Quantum.Environment
summary: " # <a name=\"summary\"></a>Resumo\n Estas funções fornecem informações sobre o ambiente em que ocorra a computação quântica."
operations:
- uid: microsoft.quantum.environment.getqubitsavailabletoborrow
  summary: >-
    Devolve o número de qubits atualmente disponíveis para empréstimo.

    Isto inclui qubits não-reutilizados; isto inclui os qubits devolvidos por `GetQubitsAvailableToUse` .
- uid: microsoft.quantum.environment.getqubitsavailabletouse
  summary: Devolve o número de qubits atualmente disponíveis para utilização.
metadata:
  ms.openlocfilehash: 7f597d8f429089b0ebf2c22cef1d1b98ea270402
  ms.sourcegitcommit: d6ac6f4345be0dd68f1bcd944f44b08e7a3cf346
  ms.translationtype: MT
  ms.contentlocale: pt-PT
  ms.lasthandoff: 09/02/2020
  ms.locfileid: "89341161"
