### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletouse
name: GetQubitsAvailableToUse
type: operation
namespace: Microsoft.Quantum.Environment
summary: Devolve o número de qubits atualmente disponíveis para utilização.
syntax: 'operation GetQubitsAvailableToUse () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      O número de qubits que poderiam ser atribuídos em comunicado. `using`

      Se a máquina-alvo que está a `-1` ser utilizada não fornecer estas informações, então é devolvida.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletoborrow
metadata:
  ms.openlocfilehash: 82d8c27064cbb234b32707aa31fb0869f66ce23c
  ms.sourcegitcommit: db23885adb7ff76cbf8bd1160d401a4f0471e549
  ms.translationtype: MT
  ms.contentlocale: pt-PT
  ms.lasthandoff: 05/01/2020
  ms.locfileid: "82682387"
